# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'twitter' do
pod 'SwiftyJSON'
pod 'SDWebImage'
pod 'MCSwipeTableViewCell'
#pod 'FormatterKit'
pod 'SVWebViewController'

end

target 'twitterTests' do

end

